/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_farwater_gnss_fakelocsample_NativeHelper */

#ifndef _Included_ru_farwater_gnss_fakelocsample_NativeHelper
#define _Included_ru_farwater_gnss_fakelocsample_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_farwater_gnss_fakelocsample_NativeHelper
 * Method:    invokeVoidMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_farwater_gnss_fakelocsample_NativeHelper_invokeVoidMethod
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
